INSERT INTO coffee (coffee_count, coffee_sort, coffee_cost) VALUES (50, 'ESPRESSO', 10);
INSERT INTO coffee (coffee_count, coffee_sort, coffee_cost) VALUES (50, 'DOUBLE ESPRESSO', 15);
INSERT INTO coffee (coffee_count, coffee_sort, coffee_cost) VALUES (50, 'SHORT MACCHIATO', 11);
INSERT INTO coffee (coffee_count, coffee_sort, coffee_cost) VALUES (50, 'LONG MACCHIATO', 14);
INSERT INTO coffee (coffee_count, coffee_sort, coffee_cost) VALUES (50, 'RISTRETTO', 9);
INSERT INTO coffee (coffee_count, coffee_sort, coffee_cost) VALUES (50, 'AMERICANO', 13);
INSERT INTO coffee (coffee_count, coffee_sort, coffee_cost) VALUES (50, 'CAFE LATTE', 12);
INSERT INTO coffee (coffee_count, coffee_sort, coffee_cost) VALUES (50, 'CAPPUCCINO', 13);
INSERT INTO coffee (coffee_count, coffee_sort, coffee_cost) VALUES (50, 'MOCHA', 10);
INSERT INTO coffee (coffee_count, coffee_sort, coffee_cost) VALUES (50, 'AFFOGATO', 9);